name: 'Deploy to AWS s3'
description: 'Deploy static website via AWS s3'
inputs:
  bucket:
    description: 's3 bucket name'
    required: true
  bucket-region:
    description: 's3 bucket region'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'Folder containing deployable files'
    required: true
runs:
  using: 'node16'
  main: 'main.js'
