name: issues
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  issues:
    types: [opened]
jobs:
  output-event:
  steps:
    runs-on: ubuntu-latest
    run: echo "Issue opened"
    run: echo "${{ toJSON(github.event) }}"
