name: issues
run-name: ${{ github.actor }} is learning GitHub Actions
on: issues
jobs:
  output-event:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo "${{ toJSON(github.event) }}"
